name: Home Mail
version: "1.1.11"
slug: mail
description: Lightweight Gmail client for Home Assistant
url: https://github.com/BrainDeLook/ha-mail-client
image: ghcr.io/braindelook/ha-mail-client-{arch}
init: false
arch:
  - amd64
  - aarch64
panel_icon: mdi:email-outline
panel_title: Mail
panel_admin: false
ingress: true
ingress_entry: /
backup: cold
options:
  gmail_email: ""
  gmail_app_password: ""
  sync_interval_minutes: 5
  cache_per_folder: 50
  default_folder: INBOX
  theme: system
  view_mode: split
  show_external_media: true
  log_level: info
schema:
  gmail_email: str
  gmail_app_password: password
  sync_interval_minutes: int(1,60)
  cache_per_folder: int(10,200)
  default_folder: list(INBOX|IMPORTANT|FLAGGED|ALL|SENT|DRAFTS|JUNK|TRASH)
  theme: list(system|light|dark|ha_dark)
  view_mode: list(split|list)
  show_external_media: bool
  log_level: list(error|warning|info|debug)
